[package]
name = "rws"
version = "15.1.0"
authors = ["Bohdan Tsap <bohdan.tsap@tutanota.com>"]
repository = "https://github.com/bohdaq/rust-web-server"
description = "rust-web-server (rws) is a static content web-server written in Rust"
edition = "2021"
license = "MIT OR Apache-2.0 OR ISC OR LGPL-3.0-or-later OR CC-BY-4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file-ext = "12.0.0"
url-search-params = "12.0.0"
url-build-parse = "11.0.0"
